TOPLEVEL_LANG = verilog
VERILOG_SOURCES = $(shell pwd)/../ov7670_uart_test.srcs/sources_1/new/vga_sync.v
TOPLEVEL = vga_sync
MODULE = test_vga_sync

include $(shell cocotb-config --makefiles)/Makefile.sim
