# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "C:/Documents/uni/term_4/ping-pong/ov7670_uart_test.runs/synth_1/.Xil/Vivado-3424-gram/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7a35tcpg236-1
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl 
    set rt::defaultWorkLibName xil_defaultlib
    rt::set_parameter defaultVhdlWorkLib xil_defaultlib

    rt::set_parameter loadVhdl2008Libs false
    rt::set_parameter loadVhdl2019Libs false
    rt::set_parameter deferParseUntilElab true
    rt::set_parameter sortHdlCommandLine true
    rt::set_parameter singleFileBasedDefaultNettype false
    # Skipping read_* RTL commands because this is post-elab optimize flow
    set rt::useElabCache true
    if {$rt::useElabCache == false} {
      rt::read_verilog -include C:/AMDDesignTools/2025.2/Vivado/data/rsb/busdef {
      C:/Documents/uni/term_4/ping-pong/ov7670_uart_test.srcs/sources_1/new/camera_config.v
      C:/Documents/uni/term_4/ping-pong/ov7670_uart_test.srcs/sources_1/new/clk_div.v
      C:/Documents/uni/term_4/ping-pong/ov7670_uart_test.srcs/sources_1/new/filters.v
      C:/Documents/uni/term_4/ping-pong/ov7670_uart_test.srcs/sources_1/new/frame_buffer.v
      C:/Documents/uni/term_4/ping-pong/ov7670_uart_test.srcs/sources_1/new/frame_capture.v
      C:/Documents/uni/term_4/ping-pong/ov7670_uart_test.srcs/sources_1/new/pixel_capture.v
      C:/Documents/uni/term_4/ping-pong/ov7670_uart_test.srcs/sources_1/new/sccb_master.v
      C:/Documents/uni/term_4/ping-pong/ov7670_uart_test.srcs/sources_1/new/uart_print.v
      C:/Documents/uni/term_4/ping-pong/ov7670_uart_test.srcs/sources_1/new/uart_tx.v
      C:/Documents/uni/term_4/ping-pong/ov7670_uart_test.srcs/sources_1/new/vga_sync.v
      C:/Documents/uni/term_4/ping-pong/ov7670_uart_test.srcs/sources_1/new/top.v
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification true
    set rt::SDCFileList C:/Documents/uni/term_4/ping-pong/ov7670_uart_test.runs/synth_1/.Xil/Vivado-3424-gram/realtime/top_synth.xdc
    rt::sdcChecksum
    set rt::top top
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter dataflowBusHighlighting false
    rt::set_parameter generateDataflowBusNetlist false
    rt::set_parameter dataFlowViewInElab false
    rt::set_parameter busViewFixBrokenConnections false
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
# MODE: 
    rt::set_parameter webTalkPath {C:/Documents/uni/term_4/ping-pong/ov7670_uart_test.cache/wt}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "C:/Documents/uni/term_4/ping-pong/ov7670_uart_test.runs/synth_1/.Xil/Vivado-3424-gram/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    rt::set_parameter incrementalOnCache ""
    rt::set_parameter doIncremental false
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
uplevel #0 { 
   if {[info exists rt::doParallel] && $rt::doParallel} {
     rt::async_wait "asyncParallelOpen"
     rt::parallel_close
   }
   $rt::db resetHdlParse
   set hsKey [rt::get_parameter helper_shm_key] 
   if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
      $rt::db killSynthHelper $hsKey
   } 
   source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  }
 return -code "error" $rt::result
}
